package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os/exec"
	"path/filepath"
	"strings"
)

type Language string

const (
	Java  Language = "Java"
	Rust  Language = "Rust"
	Go    Language = "Go"
	TypeScript Language = "TypeScript"
	JavaScript Language = "JavaScript"
	React    Language = "React"
	Vue     Language = "Vue"
	Svelte   Language = "Svelte"
	NextJs  Language = "NextJs"
	Python  Language = "Python"
)

type Result struct {
	Err error
}

func scaffold_project(output_dir string, lang Language) Result {
	logFile, err := ioutil.TempFile("", "scaffold_project")
	if err != nil {
		return Result{err}
	}
	defer logFile.Close()

	log := log.New(logFile, "log: ", log.Ldate|log.Ltime|log.Lshortfile)

	// Check that the required build tool exists on this machine. For some
	// targets (like TypeScript/JavaScript) we can still scaffold a bare
	// project even if the ecosystem tool is missing.
	tool := lang.required_tool()
	has_tool := tool_available(tool)

	if err := filepath.Walk(output_dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		return os.MkdirAll(path, os.ModePerm)
	}); err != nil {
		log.Printf("Error creating directory: %v", err)
		return Result{err}
	}

	var err_msg string
	switch lang {
	case Java:
		if !has_tool {
			err_msg = fmt.Sprintf("Required tool `%s` for %s was not found on your system. Please install it before running this migration.",
			-tool, lang)
			return Result{fmt.Errorf("%s", err_msg)}
		}
		// ...
	case Rust:
		scaffold_rust(output_dir, log)
	case Go:
		scaffold_go(output_dir, log)
	case TypeScript:
		if has_tool {
			scaffold_typescript(output_dir, log)
		} else {
			let src = output_dir + "/src"
			log.Printf("  ⚠ npm not found; created bare TypeScript src/ tree without npm/tsconfig.%s",
				log.String())
			return Result{fmt.Errorf("npm is required to scaffold TypeScript projects")}
		}
	case JavaScript:
		if has_tool {
			scaffold_javascript(output_dir, log)
		} else {
			let src = output_dir + "/src"
			log.Printf("  ⚠ npm not found; created bare JavaScript src/ tree without npm init.%s",
				log.String())
			return Result{fmt.Errorf("npm is required to scaffold JavaScript projects")}
		}
	case React, Vue, Svelte:
		if has_tool {
			scaffold_vite(output_dir, lang, log)
		} else {
			err_msg = "npm is required to scaffold Vite-based projects"
			return Result{fmt.Errorf("%s", err_msg)}
		}
	case NextJs:
		if has_tool {
			scaffold_nextjs(output_dir, log)
		} else {
			err_msg = "npm/npx is required to scaffold Next.js projects"
			return Result{fmt.Errorf("%s", err_msg)}
		}
	case Python:
		scaffold_python(output_dir, log)
	case Java:
		scaffold_java(output_dir, log)
	}

	logFile.Sync()
	return Result{fmt.Errorf("successfuly scaffolded project at %s", output_dir)}
}

// Per-language scaffolders

func scaffold_rust(dir string, log *log.Logger) (Result) {
	let src = dir + "/src"
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		return os.MkdirAll(path, os.ModePerm)
	})

	// Cargo.toml
	let cargo_toml = fmt.Sprintf(`
[package]
name = "%s"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`, filepath.Base(dir))

	if _, err := os.Create(dir + "/Cargo.toml"); err != nil {
		log.Printf("Error writing Cargo.toml: %v%s", err, log.String())
		return Result{fmt.Errorf("Error writing Cargo.toml: %v%s", err, log.String())}
	} else {
		if _, err := os.WriteFile(dir + "/Cargo.toml", []byte(cargo_toml), 0644); err != nil {
			log.Printf("Error writing Cargo.toml: %v%s", err, log.String())
			return Result{fmt.Errorf("Error writing Cargo.toml: %v%s", err, log.String())}
		}
	}

	// src/lib.rs placeholder
	if _, err := os.WriteFile(dir + "/src/lib.rs", []byte("// Auto-generated by astra migrate\n"), 0644); err != nil {
		log.Printf("Error writing lib.rs: %v%s", err, log.String())
		return Result{fmt.Errorf("Error writing lib.rs: %v%s", err, log.String())}
	}

	log.Printf("  ✓ Created Rust project at %s%s", dir, log.String())

	// Try running cargo check to pull deps
	if _, err := exec.Command("cargo", "check").Output(); err != nil {
		log.Printf("  ⚠ cargo check didn't succeed — deps may need manual install%s", log.String())
	} else {
		log.Printf("  ✓ Dependencies installed (cargo check passed)%s", log.String())
	}

	return Result{}
}

func scaffold_go(dir string, log *log.Logger) (Result) {
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		return os.MkdirAll(path, os.ModePerm)
	})

	let mod_name = filepath.Base(dir)
	let status, err := exec.Command("go", "mod", "init", mod_name).Output()
	if err != nil {
		log.Printf("Error initializing module: %v%s", err, log.String())
		return Result{fmt.Errorf("Error initializing module: %v%s", err, log.String())}
	}

	if !strings.Contains(string(status), "module found") {
		let go_mod = fmt.Sprintf("module %s\ngo 1.21\n", mod_name)
		if _, err := os.WriteFile(dir + "/go.mod", []byte(go_mod), 0644); err != nil {
			log.Printf("Error initializing module: %v%s", err, log.String())
			return Result{fmt.Errorf("Error initializing module: %v%s", err, log.String())}
		}
		log.Printf("  ✓ Created go.mod manually%s", log.String())
	} else {
		log.Printf("  ✓ Initialized Go module `%s`%s", mod_name, log.String())
	}

	return Result{}
}

func scaffold_typescript(dir string, log *log.Logger) (Result) {
	let src = dir + "/src"
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		return os.MkdirAll(path, os.ModePerm)
	})

	// npm init
	if _, err := exec.Command("npm", "init", "-y").Output(); err != nil {
		log.Printf("Error initializing project: %v%s", err, log.String())
		return Result{fmt.Errorf("Error initializing project: %v%s", err, log.String())}
	} else {
		log.Printf("  ✓ npm init -y%s", log.String())
	}

	// Install typescript
	if _, err := exec.Command("npm", "install", "--save-dev", "typescript", "@types/node").Output(); err != nil {
		log.Printf("Error installing typescript: %v%s", err, log.String())
		return Result{fmt.Errorf("Error installing typescript: %v%s", err, log.String())}
	} else {
		log.Printf("  ✓ Installed typescript, @types/node%s", log.String())
	}

	// tsconfig
	tsconfig := `
{
	"compilerOptions": {
		"target": "ES2020",
		"module": "commonjs",
		"outDir": "./dist",
		"rootDir": "./src",
		"strict": true,
		"esModuleInterop": true,
		"skipLibCheck": true
	},
	"include": ["src/**/*"]
}
`
	if _, err := os.WriteFile(dir + "/tsconfig.json", []byte(tsconfig), 0644); err != nil {
		log.Printf("Error writing tsconfig.json: %v%s", err, log.String())
		return Result{fmt.Errorf("Error writing tsconfig.json: %v%s", err, log.String())}
	} else {
		log.Printf("  ✓ Created tsconfig.json%s", log.String())
	}

	return Result{}
}

func scaffold_javascript(dir string, log *log.Logger) (Result) {
	let src = dir + "/src"
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err