// TODO: use anyhow::{anyhow, Result};

// TODO: use super::detect::Language;
// TODO: use crate::model::CodexModel;

// // ---------------------------------------------------------------------------
// // Translator trait
// // ---------------------------------------------------------------------------

// /// A translator converts source code from one language to another.
// pub trait Translator {
// fn translate(

// &self,
// source_code: &str,
// from: Language,
// to: Language,
// ) -> Result<String>;
// }

// // ---------------------------------------------------------------------------
// // Rule-based translator
// // ---------------------------------------------------------------------------

export interface RuleBasedTranslator; {
}

// }

// impl Translator for RuleBasedTranslator {
// fn translate(

// &self,
// source_code: &str,
// from: Language,
// to: Language,
// ) -> Result<String> {
// match (from, to) {
// (Language::TypeScript, Language::Rust) => Ok(translate_ts_to_rust(source_code)),
// (Language::JavaScript, Language::Rust) => Ok(translate_ts_to_rust(source_code)),
// (Language::Python, Language::Rust) => Ok(translate_py_to_rust(source_code)),
// (Language::TypeScript, Language::Python) => Ok(translate_ts_to_python(source_code)),
// (Language::TypeScript, Language::Go) => Ok(translate_ts_to_go(source_code)),
// (Language::Python, Language::Go) => Ok(translate_py_to_go(source_code)),
// (Language::Python, Language::TypeScript) => Ok(translate_py_to_ts(source_code)),
// (Language::Rust, Language::TypeScript) => Ok(translate_rust_to_ts(source_code)),
// _ => Err(anyhow!(
// "Rule-based translation from {} to {} is not yet supported",
// from,
// to
// )),
// }
// }
// }

// // ---------------------------------------------------------------------------
// // AI-powered translator
// // ---------------------------------------------------------------------------

export interface AiTranslator<'a> {
  model: any;
}


// impl<'a> AiTranslator<'a> {
export function new(model: any): any {
  // Self { model }
}

// }

// impl<'a> Translator for AiTranslator<'a> {
// fn translate(

// &self,
// source_code: &str,
// from: Language,
// to: Language,
// ) -> Result<String> {
// let prompt = format!(
// "You are an expert code translator. Translate the following {} code into idiomatic {}.\n\
// Rules:\n\
// - Preserve function names and signatures as closely as possible\n\
// - Use idiomatic patterns for the target language\n\
// - Do not add comments or explanations\n\
// - Output ONLY the translated code, no markdown fences, no extra text\n\
// - Translate ALL code in the file, not just functions\n\
// - Map types idiomatically (e.g. string → &str/String, number → i32/f64, etc.)\n\n\
// Source {} code:\n{}\n",
// from, to, from, source_code
// );

// let raw = self.model.complete(&prompt)?;
// Ok(strip_markdown_fences(&raw))
// }
// }

// // ---------------------------------------------------------------------------
// // Hybrid translator: AI first, rules fallback
// // ---------------------------------------------------------------------------

export interface HybridTranslator<'a> {
  rules: any;
  ai: any;
}


// impl<'a> HybridTranslator<'a> {
export function new(model: any): any {
  // Self {
  // rules: RuleBasedTranslator::new(),
  // ai: model.map(AiTranslator::new),
  // }
}

// }

// impl<'a> Translator for HybridTranslator<'a> {
// fn translate(

// &self,
// source_code: &str,
// from: Language,
// to: Language,
// ) -> Result<String> {
// // If we have an AI model, try it first.
// if let Some(ai) = &self.ai {
// if let Ok(result) = ai.translate(source_code, from, to) {
// if !result.trim().is_empty() {
// return Ok(result);
// }
// }
// }

// // Fall back to rule-based translator
// match self.rules.translate(source_code, from, to) {
// Ok(result) if !result.trim().is_empty() => Ok(result),
// _ => Err(anyhow!(
// "Translation produced empty output for {} → {} and no usable \
// result was generated by AI or rules.",
// from,
// to
// )),
// }
// }
// }

// // ===========================================================================
// // Language-specific rule-based translators
// // ===========================================================================

// // ---------------------------------------------------------------------------
// // TypeScript / JavaScript → Rust
// // ---------------------------------------------------------------------------

export function translate_ts_to_rust(source: string): string {
  // let lines: Vec<&str> = source.lines().collect();
  // let mut out = String::new();
  // let mut i = 0;
  // 
  // while i < lines.len() {
  // let line = lines[i].trim();
  // 
  // // Skip empty lines / comments
  // if line.is_empty() {
  // out.push('\n');
  // i += 1;
  // continue;
  // }
  // 
  // // Import statements → use statements (as comments for now)
  // if line.starts_with("import ") {
  // out.push_str(&format!("// TODO: {}\n", line));
  // i += 1;
  // continue;
  // }
  // 
  // // Interface / type → struct
  // if line.starts_with("export interface ") || line.starts_with("interface ") {
  // let (rust_struct, consumed) = translate_ts_interface_to_rust(&lines, i);
  // out.push_str(&rust_struct);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // // Type alias
  // if line.starts_with("export type ") || line.starts_with("type ") {
  // out.push_str(&format!("// TODO: {}\n", line));
  // i += 1;
  // continue;
  // }
  // 
  // // Class → struct + impl
  // if line.starts_with("export class ") || line.starts_with("class ") {
  // let (rust_code, consumed) = translate_ts_class_to_rust(&lines, i);
  // out.push_str(&rust_code);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // // export function / function
  // if line.starts_with("export function ")
  // || line.starts_with("function ")
  // || line.starts_with("export async function ")
  // || line.starts_with("async function ")
  // {
  // let (rust_fn, consumed) = translate_ts_function_to_rust(&lines, i);
  // out.push_str(&rust_fn);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // // Arrow functions: export const name = (...) => { ... }
  // if (line.starts_with("export const ") || line.starts_with("const "))
  // && line.contains("=>")
  // {
  // let (rust_fn, consumed) = translate_ts_arrow_to_rust(&lines, i);
  // out.push_str(&rust_fn);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // // Variable declarations
  // if line.starts_with("export const ")
  // || line.starts_with("const ")
  // || line.starts_with("let ")
  // || line.starts_with("var ")
  // {
  // out.push_str(&translate_ts_variable_to_rust(line));
  // out.push('\n');
  // i += 1;
  // continue;
  // }
  // 
  // // Anything else: pass through as comment
  // out.push_str(&format!("// {}\n", line));
  // i += 1;
  // }
  // 
  // out
}


// // ---------------------------------------------------------------------------
// // Rust → TypeScript
// // ---------------------------------------------------------------------------

export function translate_rust_to_ts(source: string): string {
  // let lines: Vec<&str> = source.lines().collect();
  // let mut out = String::new();
  // let mut i = 0;
  // 
  // while i < lines.len() {
  // let line = lines[i];
  // let trimmed = line.trim();
  // 
  // if trimmed.is_empty() {
  // out.push('\n');
  // i += 1;
  // continue;
  // }
  // 
  // if trimmed.starts_with("use ")
  // || trimmed.starts_with("mod ")
  // || trimmed.starts_with("extern crate ")
  // {
  // out.push_str(&format!("// TODO: {}\n", trimmed));
  // i += 1;
  // continue;
  // }
  // 
  // if trimmed.starts_with("pub struct ") || trimmed.starts_with("struct ") {
  // let (ts_iface, consumed) = translate_rust_struct_to_ts(&lines, i);
  // out.push_str(&ts_iface);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // if trimmed.starts_with("pub enum ") || trimmed.starts_with("enum ") {
  // let (ts_enum, consumed) = translate_rust_enum_to_ts(&lines, i);
  // out.push_str(&ts_enum);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // if trimmed.starts_with("pub fn ") || trimmed.starts_with("fn ") {
  // let (ts_fn, consumed) = translate_rust_fn_to_ts(&lines, i);
  // out.push_str(&ts_fn);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // out.push_str(&format!("// {}\n", trimmed));
  // i += 1;
  // }
  // 
  // out
}


export function translate_rust_struct_to_ts(lines: any[], start: number): any {
  // let header = lines[start].trim();
  // let name = header
  // .split_whitespace()
  // .skip_while(|p| *p != "struct")
  // .nth(1)
  // .unwrap_or("Unknown");
  // 
  // let mut out = String::new();
  // out.push_str(&format!("export interface {} {{\n", name));
  // 
  // let mut i = start + 1;
  // while i < lines.len() {
  // let line = lines[i].trim();
  // if line.starts_with('}') {
  // i += 1;
  // break;
  // }
  // if line.is_empty() || line.starts_with("//") {
  // i += 1;
  // continue;
  // }
  // if let Some((field_name, ty)) = line.split_once(':') {
  // let field_name = field_name
  // .trim_start_matches("pub ")
  // .trim()
  // .trim_end_matches(',');
  // let ty = ty.trim().trim_end_matches(',').trim_end_matches(',');
  // let ts_type = map_rust_type_ts(ty);
  // out.push_str(&format!("  {}: {};\n", field_name, ts_type));
  // }
  // i += 1;
  // }
  // 
  // out.push_str("}\n");
  // (out, i - start)
}


export function translate_rust_enum_to_ts(lines: any[], start: number): any {
  // let header = lines[start].trim();
  // let name = header
  // .split_whitespace()
  // .skip_while(|p| *p != "enum")
  // .nth(1)
  // .unwrap_or("Unknown");
  // 
  // let mut variants = Vec::new();
  // let mut i = start + 1;
  // while i < lines.len() {
  // let line = lines[i].trim();
  // if line.starts_with('}') {
  // i += 1;
  // break;
  // }
  // if line.is_empty() || line.starts_with("//") {
  // i += 1;
  // continue;
  // }
  // let clean = line.trim_end_matches(',').trim();
  // if !clean.is_empty() && !clean.contains('{') && !clean.contains('(') {
  // variants.push(clean.to_string());
  // }
  // i += 1;
  // }
  // 
  // let mut out = String::new();
  // if variants.is_empty() {
  // out.push_str(&format!("export type {} = string;\n", name));
  // } else {
  // out.push_str(&format!("export type {} =\n", name));
  // for (idx, v) in variants.iter().enumerate() {
  // if idx == variants.len() - 1 {
  // out.push_str(&format!("  | \"{}\";\n", v));
  // } else {
  // out.push_str(&format!("  | \"{}\"\n", v));
  // }
  // }
  // }
  // (out, i - start)
}


export function translate_rust_fn_to_ts(lines: any[], start: number): any {
  // let header = lines[start].trim();
  // let clean = header
  // .trim_start_matches("pub ")
  // .trim_start_matches("fn ")
  // .trim();
  // 
  // let open_paren = match clean.find('(') {
  // Some(p) => p,
  // None => return (format!("// {}\n", header), 1),
  // };
  // let close_paren = match clean.find(')') {
  // Some(p) => p,
  // None => return (format!("// {}\n", header), 1),
  // };
  // 
  // let name = &clean[..open_paren];
  // let params_str = &clean[open_paren + 1..close_paren];
  // let after_paren = clean[close_paren + 1..].trim();
  // 
  // let ret_type = if let Some(arrow_pos) = after_paren.find("->") {
  // let ty = after_paren[arrow_pos + 2..].trim().trim_end_matches('{').trim();
  // map_rust_type_ts(ty)
  // } else {
  // "void"
  // };
  // 
  // let params = translate_rust_params_ts(params_str);
  // let (body, consumed) = collect_braced_body(lines, start);
  // 
  // let mut out = String::new();
  // out.push_str(&format!("export function {}({}): {} {{\n", name, params, ret_type));
  // if body.is_empty() {
  // out.push_str("  // TODO: implement\n");
  // } else {
  // for body_line in &body {
  // out.push_str(&format!("  // {}\n", body_line.trim()));
  // }
  // }
  // out.push_str("}\n");
  // 
  // (out, consumed)
  // }
  // 
  // fn translate_ts_interface_to_rust(lines: &[&str], start: usize) -> (String, usize) {
  // let header = lines[start].trim();
  // let name = header
  // .trim_start_matches("export ")
  // .trim_start_matches("interface ")
  // .split(|c: char| c == '{' || c == ' ' || c == '<')
  // .next()
  // .unwrap_or("Unknown")
  // .trim();
  // 
  // let mut out = String::new();
  // out.push_str(&format!("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\npub struct {} {{\n", name));
  // 
  // let mut i = start + 1;
  // while i < lines.len() {
  // let line = lines[i].trim();
  // if line == "}" || line.starts_with("}") {
  // i += 1;
  // break;
  // }
  // // Parse field: name: type; or name?: type;
  // if let Some((field_name, ts_type)) = parse_ts_field(line) {
  // let optional = field_name.ends_with('?');
  // let clean_name = field_name.trim_end_matches('?');
  // let rust_type = map_ts_type_rust(ts_type);
  // if optional {
  // out.push_str(&format!("    pub {}: Option<{}>,\n", to_snake_case(clean_name), rust_type));
  // } else {
  // out.push_str(&format!("    pub {}: {},\n", to_snake_case(clean_name), rust_type));
  // }
  // }
  // i += 1;
  // }
  // 
  // out.push_str("}\n");
  // (out, i - start)
  // }
  // 
  // fn translate_ts_class_to_rust(lines: &[&str], start: usize) -> (String, usize) {
  // let header = lines[start].trim();
  // let name = header
  // .trim_start_matches("export ")
  // .trim_start_matches("class ")
  // .split(|c: char| c == '{' || c == ' ' || c == '<')
  // .next()
  // .unwrap_or("Unknown")
  // .trim();
  // 
  // let mut fields = Vec::new();
  // let mut methods = Vec::new();
  // 
  // let mut i = start + 1;
  // let mut brace_depth = 1;
  // 
  // while i < lines.len() && brace_depth > 0 {
  // let line = lines[i].trim();
  // 
  // for c in line.chars() {
  // match c {
  // '{' => brace_depth += 1,
  // '}' => brace_depth -= 1,
  // _ => {}
  // }
  // }
  // 
  // if brace_depth == 0 {
  // i += 1;
  // break;
  // }
  // 
  // // Constructor fields
  // if line.starts_with("constructor(") || line.contains("constructor(") {
  // // Extract params as fields
  // if let Some(params_start) = line.find('(') {
  // if let Some(params_end) = line.find(')') {
  // let params = &line[params_start + 1..params_end];
  // for param in params.split(',') {
  // let p = param
  // .trim()
  // .trim_start_matches("private ")
  // .trim_start_matches("public ")
  // .trim_start_matches("readonly ");
  // if let Some((name, ty)) = p.split_once(':') {
  // fields.push((
  // name.trim().to_string(),
  // map_ts_type_rust(ty.trim()).to_string(),
  // ));
  // }
  // }
  // }
  // }
  // }
  // // Class property
  // else if line.contains(':') && !line.contains('(') && !line.starts_with("//") {
  // let clean = line.trim_start_matches("private ")
  // .trim_start_matches("public ")
  // .trim_start_matches("readonly ");
  // if let Some((name, ty)) = clean.split_once(':') {
  // let ty_clean = ty.trim().trim_end_matches(';');
  // fields.push((
  // name.trim().to_string(),
  // map_ts_type_rust(ty_clean).to_string(),
  // ));
  // }
  // }
  // // Methods
  // else if (line.contains('(') && line.contains(')'))
  // && !line.starts_with("constructor")
  // && !line.starts_with("//")
  // {
  // let method_line = line
  // .trim_start_matches("async ")
  // .trim_start_matches("public ")
  // .trim_start_matches("private ");
  // methods.push(method_line.to_string());
  // }
  // 
  // i += 1;
  // }
  // 
  // let mut out = String::new();
  // out.push_str(&format!("pub struct {} {{\n", name));
  // for (fname, ftype) in &fields {
  // out.push_str(&format!("    pub {}: {},\n", to_snake_case(fname), ftype));
  // }
  // out.push_str("}\n\n");
  // 
  // out.push_str(&format!("impl {} {{\n", name));
  // out.push_str("    pub fn new(");
  // let params: Vec<String> = fields
  // .iter()
  // .map(|(n, t)| format!("{}: {}", to_snake_case(n), t))
  // .collect();
  // out.push_str(&params.join(", "));
  // out.push_str(&format!(") -> Self {{\n        Self {{\n"));
  // for (fname, _) in &fields {
  // let snake = to_snake_case(fname);
  // out.push_str(&format!("            {},\n", snake));
  // }
  // out.push_str("        }\n    }\n");
  // 
  // for method in &methods {
  // out.push_str(&format!("\n    // TODO: translate method: {}\n", method));
  // }
  // 
  // out.push_str("}\n");
  // 
  // (out, i - start)
  // }
  // 
  // fn translate_ts_function_to_rust(lines: &[&str], start: usize) -> (String, usize) {
  // let header = lines[start].trim();
  // let clean = header
  // .trim_start_matches("export ")
  // .trim_start_matches("async ")
  // .trim_start_matches("function ")
  // .trim();
  // 
  // let open_paren = match clean.find('(') {
  // Some(p) => p,
  // None => return (format!("// {}\n", header), 1),
  // };
  // let close_paren = match clean.find(')') {
  // Some(p) => p,
  // None => return (format!("// {}\n", header), 1),
  // };
  // 
  // let name = &clean[..open_paren];
  // let params_str = &clean[open_paren + 1..close_paren];
  // let after_paren = clean[close_paren + 1..].trim();
  // 
  // let ret_type = if let Some(colon_pos) = after_paren.find(':') {
  // let ty = after_paren[colon_pos + 1..]
  // .trim()
  // .trim_end_matches('{')
  // .trim()
  // .trim_start_matches("Promise<")
  // .trim_end_matches('>');
  // map_ts_type_rust(ty)
  // } else {
  // "()"
  // };
  // 
  // let params = translate_ts_params_rust(params_str);
  // 
  // // Collect body
  // let (body, consumed) = collect_braced_body(lines, start);
  // 
  // let mut out = String::new();
  // out.push_str(&format!("pub fn {}({}) -> {} {{\n", to_snake_case(name), params, ret_type));
  // for body_line in &body {
  // out.push_str(&format!("    // TODO: {}\n", body_line.trim()));
  // }
  // if body.is_empty() {
  // match ret_type {
  // "()" => {}
  // "String" => out.push_str("    String::new()\n"),
  // "i32" | "i64" | "f64" => out.push_str("    0\n"),
  // "bool" => out.push_str("    false\n"),
  // _ => out.push_str("    todo!()\n"),
  // }
  // }
  // out.push_str("}\n");
  // 
  // (out, consumed)
  // }
  // 
  // fn translate_ts_arrow_to_rust(lines: &[&str], start: usize) -> (String, usize) {
  // let header = lines[start].trim();
  // let clean = header
  // .trim_start_matches("export ")
  // .trim_start_matches("const ")
  // .trim();
  // 
  // // name = (params) => ...
  // let eq_pos = match clean.find('=') {
  // Some(p) => p,
  // None => return (format!("// {}\n", header), 1),
  // };
  // 
  // let name = clean[..eq_pos].trim();
  // let after_eq = clean[eq_pos + 1..].trim();
  // 
  // // Try to extract params from (params): RetType =>
  // let (params_str, ret_hint) = if let Some(paren_start) = after_eq.find('(') {
  // if let Some(paren_end) = after_eq.find(')') {
  // let p = &after_eq[paren_start + 1..paren_end];
  // let after = after_eq[paren_end + 1..].trim();
  // let ret = if let Some(colon_pos) = after.find(':') {
  // let ty = after[colon_pos + 1..]
  // .trim()
  // .split("=>")
  // .next()
  // .unwrap_or("")
  // .trim();
  // map_ts_type_rust(ty)
  // } else {
  // "()"
  // };
  // (p.to_string(), ret)
  // } else {
  // (String::new(), "()")
  // }
  // } else {
  // (String::new(), "()")
  // };
  // 
  // let params = translate_ts_params_rust(&params_str);
  // let (body, consumed) = collect_braced_body(lines, start);
  // 
  // let mut out = String::new();
  // out.push_str(&format!("pub fn {}({}) -> {} {{\n", to_snake_case(name), params, ret_hint));
  // for body_line in &body {
  // out.push_str(&format!("    // TODO: {}\n", body_line.trim()));
  // }
  // if body.is_empty() {
  // out.push_str("    todo!()\n");
  // }
  // out.push_str("}\n");
  // 
  // (out, consumed)
  // }
  // 
  // fn translate_ts_variable_to_rust(line: &str) -> String {
  // let clean = line
  // .trim()
  // .trim_start_matches("export ")
  // .trim_start_matches("const ")
  // .trim_start_matches("let ")
  // .trim_start_matches("var ")
  // .trim_end_matches(';');
  // 
  // if let Some((name, value)) = clean.split_once('=') {
  // let name = name.split(':').next().unwrap_or(name).trim();
  // let value = value.trim();
  // format!("pub const {}: &str = {}; // TODO: fix type", name.to_uppercase(), value)
  // } else {
  // format!("// {}", line)
  // }
  // }
  // 
  // // ---------------------------------------------------------------------------
  // // Python → Rust
  // // ---------------------------------------------------------------------------
  // 
  // fn translate_py_to_rust(source: &str) -> String {
  // let lines: Vec<&str> = source.lines().collect();
  // let mut out = String::new();
  // let mut i = 0;
  // 
  // while i < lines.len() {
  // let line = lines[i];
  // let trimmed = line.trim();
  // 
  // if trimmed.is_empty() {
  // out.push('\n');
  // i += 1;
  // continue;
  // }
  // 
  // // Import → comment
  // if trimmed.starts_with("import ") || trimmed.starts_with("from ") {
  // out.push_str(&format!("// TODO: {}\n", trimmed));
  // i += 1;
  // continue;
  // }
  // 
  // // Class
  // if trimmed.starts_with("class ") {
  // let (rust_code, consumed) = translate_py_class_to_rust(&lines, i);
  // out.push_str(&rust_code);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // // Function
  // if trimmed.starts_with("def ") || trimmed.starts_with("async def ") {
  // let (rust_fn, consumed) = translate_py_function_to_rust(&lines, i);
  // out.push_str(&rust_fn);
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // 
  // // Decorator
  // if trimmed.starts_with('@') {
  // out.push_str(&format!("// {}\n", trimmed));
  // i += 1;
  // continue;
  // }
  // 
  // // Anything else
  // out.push_str(&format!("// {}\n", trimmed));
  // i += 1;
  // }
  // 
  // out
  // }
  // 
  // fn translate_py_function_to_rust(lines: &[&str], start: usize) -> (String, usize) {
  // let header = lines[start].trim();
  // let clean = header
  // .trim_start_matches("async ")
  // .trim_start_matches("def ")
  // .trim_end_matches(':');
  // 
  // let open_paren = match clean.find('(') {
  // Some(p) => p,
  // None => return (format!("// {}\n", header), 1),
  // };
  // let close_paren = match clean.rfind(')') {
  // Some(p) => p,
  // None => return (format!("// {}\n", header), 1),
  // };
  // 
  // let name = &clean[..open_paren];
  // let params_str = &clean[open_paren + 1..close_paren];
  // let after_close = clean[close_paren + 1..].trim();
  // 
  // let ret_type = if let Some(arrow_pos) = after_close.find("->") {
  // let ty = after_close[arrow_pos + 2..].trim();
  // map_py_type_rust(ty)
  // } else {
  // "()"
  // };
  // 
  // let params = translate_py_params_rust(params_str);
  // 
  // // Collect indented body
  // let (body, consumed) = collect_py_body(lines, start);
  // 
  // let mut out = String::new();
  // out.push_str(&format!("pub fn {}({}) -> {} {{\n", to_snake_case(name), params, ret_type));
  // for body_line in &body {
  // out.push_str(&format!("    // TODO: {}\n", body_line.trim()));
  // }
  // if body.is_empty() {
  // out.push_str("    todo!()\n");
  // }
  // out.push_str("}\n");
  // 
  // (out, consumed)
  // }
  // 
  // fn translate_py_class_to_rust(lines: &[&str], start: usize) -> (String, usize) {
  // let header = lines[start].trim();
  // let name = header
  // .trim_start_matches("class ")
  // .split(|c: char| c == '(' || c == ':' || c == ' ')
  // .next()
  // .unwrap_or("Unknown")
  // .trim();
  // 
  // let mut fields: Vec<(String, String)> = Vec::new();
  // let mut methods: Vec<String> = Vec::new();
  // 
  // let (body_lines, consumed) = collect_py_body(lines, start);
  // 
  // for bline in &body_lines {
  // let t = bline.trim();
  // if t.starts_with("self.") && t.contains('=') {
  // if let Some(dot_field) = t.strip_prefix("self.") {
  // if let Some((fname, _)) = dot_field.split_once('=') {
  // let fname = fname.trim().trim_end_matches(':').trim();
  // // Avoid duplicates
  // if !fields.iter().any(|(n, _)| n == fname) {
  // fields.push((fname.to_string(), "String".to_string()));
  // }
  // }
  // }
  // }
  // if t.starts_with("def ") || t.starts_with("async def ") {
  // methods.push(t.to_string());
  // }
  // }
  // 
  // let mut out = String::new();
  // out.push_str(&format!("pub struct {} {{\n", name));
  // for (fname, ftype) in &fields {
  // out.push_str(&format!("    pub {}: {},\n", to_snake_case(fname), ftype));
  // }
  // out.push_str("}\n\n");
  // 
  // out.push_str(&format!("impl {} {{\n", name));
  // for method in &methods {
  // out.push_str(&format!("    // TODO: translate method: {}\n", method));
  // }
  // out.push_str("}\n");
  // 
  // (out, consumed)
  // }
  // 
  // fn translate_py_params_rust(params_str: &str) -> String {
  // let mut parts = Vec::new();
  // for part in params_str.split(',') {
  // let trimmed = part.trim();
  // if trimmed.is_empty() || trimmed == "self" {
  // continue;
  // }
  // if let Some((name, ty)) = trimmed.split_once(':') {
  // let name = name.trim().trim_start_matches('*');
  // let ty = ty.split('=').next().unwrap_or("").trim();
  // let rust_ty = map_py_type_rust(ty);
  // parts.push(format!("{}: {}", name, rust_ty));
  // } else {
  // let name = trimmed.split('=').next().unwrap_or(trimmed).trim();
  // parts.push(format!("{}: /* unknown */", name));
  // }
  // }
  // parts.join(", ")
  // }
  // 
  // fn map_py_type_rust(py_type: &str) -> &'static str {
  // match py_type.trim() {
  // "str" => "String",
  // "int" => "i64",
  // "float" => "f64",
  // "bool" => "bool",
  // "None" => "()",
  // "list" | "List" => "Vec<String>",
  // "dict" | "Dict" => "std::collections::HashMap<String, String>",
  // "bytes" => "Vec<u8>",
  // _ => "String",
  // }
  // }
  // 
  // // ---------------------------------------------------------------------------
  // // TypeScript → Python
  // // ---------------------------------------------------------------------------
  // 
  // fn translate_ts_to_python(source: &str) -> String {
  // let lines: Vec<&str> = source.lines().collect();
  // let mut out = String::new();
  // let mut i = 0;
  // 
  // while i < lines.len() {
  // let line = lines[i].trim();
  // if line.is_empty() {
  // out.push('\n');
  // i += 1;
  // continue;
  // }
  // 
  // if line.starts_with("import ") {
  // out.push_str(&format!("# TODO: {}\n", line));
  // i += 1;
  // continue;
  // }
  // 
  // if line.starts_with("export function ") || line.starts_with("function ") {
  // let clean = line
  // .trim_start_matches("export ")
  // .trim_start_matches("async ")
  // .trim_start_matches("function ")
  // .trim();
  // 
  // if let Some(open) = clean.find('(') {
  // if let Some(close) = clean.find(')') {
  // let name = &clean[..open];
  // let params = &clean[open + 1..close];
  // let py_params = translate_ts_params_python(params);
  // let (body, consumed) = collect_braced_body(lines.as_slice(), i);
  // out.push_str(&format!("def {}({}):\n", to_snake_case(name), py_params));
  // if body.is_empty() {
  // out.push_str("    pass\n");
  // } else {
  // for bl in &body {
  // out.push_str(&format!("    # TODO: {}\n", bl.trim()));
  // }
  // }
  // out.push('\n');
  // i += consumed;
  // continue;
  // }
  // }
  // }
  // 
  // out.push_str(&format!("# {}\n", line));
  // i += 1;
  // }
  // 
  // out
  // }
  // 
  // // ---------------------------------------------------------------------------
  // // TypeScript → Go
  // // ---------------------------------------------------------------------------
  // 
  // fn translate_ts_to_go(source: &str) -> String {
  // let lines: Vec<&str> = source.lines().collect();
  // let mut out = String::new();
  // out.push_str("package main\n\n");
  // let mut i = 0;
  // 
  // while i < lines.len() {
  // let line = lines[i].trim();
  // if line.is_empty() {
  // out.push('\n');
  // i += 1;
  // continue;
  // }
  // 
  // if line.starts_with("import ") {
  // out.push_str(&format!("// TODO: {}\n", line));
  // i += 1;
  // continue;
  // }
  // 
  // if line.starts_with("export function ") || line.starts_with("function ") {
  // let clean = line
  // .trim_start_matches("export ")
  // .trim_start_matches("async ")
  // .trim_start_matches("function ");
  // 
  // if let Some(open) = clean.find('(') {
  // if let Some(close) = clean.find(')') {
  // let name = &clean[..open];
  // let params = &clean[open + 1..close];
  // let after = clean[close + 1..].trim();
  // let ret_type = if let Some(colon) = after.find(':') {
  // let ty = after[colon + 1..].trim().trim_end_matches('{').trim();
  // map_ts_type_go(ty)
  // } else {
  // ""
  // };
  // let go_params = translate_ts_params_go(params);
  // let (body, consumed) = collect_braced_body(lines.as_slice(), i);
  // 
  // let go_name = to_pascal_case(name);
  // if ret_type.is_empty() {
  // out.push_str(&format!("func {}({}) {{\n", go_name, go_params));
  // } else {
  // out.push_str(&format!("func {}({}) {} {{\n", go_name, go_params, ret_type));
  // }
  // for bl in &body {
  // out.push_str(&format!("\t// TODO: {}\n", bl.trim()));
  // }
  // out.push_str("}\n\n");
  // i += consumed;
  // continue;
  // }
  // }
  // }
  // 
  // out.push_str(&format!("// {}\n", line));
  // i += 1;
  // }
  // 
  // out
  // }
  // 
  // // ---------------------------------------------------------------------------
  // // Python → Go
  // // ---------------------------------------------------------------------------
  // 
  // fn translate_py_to_go(source: &str) -> String {
  // let lines: Vec<&str> = source.lines().collect();
  // let mut out = String::new();
  // out.push_str("package main\n\n");
  // let mut i = 0;
  // 
  // while i < lines.len() {
  // let line = lines[i].trim();
  // if line.is_empty() {
  // out.push('\n');
  // i += 1;
  // continue;
  // }
  // 
  // if line.starts_with("import ") || line.starts_with("from ") {
  // out.push_str(&format!("// TODO: {}\n", line));
  // i += 1;
  // continue;
  // }
  // 
  // if line.starts_with("def ") || line.starts_with("async def ") {
  // let clean = line
  // .trim_start_matches("async ")
  // .trim_start_matches("def ")
  // .trim_end_matches(':');
  // 
  // if let Some(open) = clean.find('(') {
  // if let Some(close) = clean.rfind(')') {
  // let name = &clean[..open];
  // let params = &clean[open + 1..close];
  // let after = clean[close + 1..].trim();
  // let ret_type = if let Some(arrow) = after.find("->") {
  // map_py_type_go(after[arrow + 2..].trim())
  // } else {
  // ""
  // };
  // let go_params = translate_py_params_go(params);
  // let (body, consumed) = collect_py_body(lines.as_slice(), i);
  // 
  // let go_name = to_pascal_case(name);
  // if ret_type.is_empty() {
  // out.push_str(&format!("func {}({}) {{\n", go_name, go_params));
  // } else {
  // out.push_str(&format!("func {}({}) {} {{\n", go_name, go_params, ret_type));
  // }
  // for bl in &body {
  // out.push_str(&format!("\t// TODO: {}\n", bl.trim()));
  // }
  // out.push_str("}\n\n");
  // i += consumed;
  // continue;
  // }
  // }
  // }
  // 
  // out.push_str(&format!("// {}\n", line));
  // i += 1;
  // }
  // 
  // out
  // }
  // 
  // // ---------------------------------------------------------------------------
  // // Python → TypeScript
  // // ---------------------------------------------------------------------------
  // 
  // fn translate_py_to_ts(source: &str) -> String {
  // let lines: Vec<&str> = source.lines().collect();
  // let mut out = String::new();
  // let mut i = 0;
  // 
  // while i < lines.len() {
  // let line = lines[i].trim();
  // if line.is_empty() {
  // out.push('\n');
  // i += 1;
  // continue;
  // }
  // 
  // if line.starts_with("import ") || line.starts_with("from ") {
  // out.push_str(&format!("// TODO: {}\n", line));
  // i += 1;
  // continue;
  // }
  // 
  // if line.starts_with("def ") || line.starts_with("async def ") {
  // let is_async = line.starts_with("async ");
  // let clean = line
  // .trim_start_matches("async ")
  // .trim_start_matches("def ")
  // .trim_end_matches(':');
  // 
  // if let Some(open) = clean.find('(') {
  // if let Some(close) = clean.rfind(')') {
  // let name = &clean[..open];
  // let params = &clean[open + 1..close];
  // let after = clean[close + 1..].trim();
  // let ret_type = if let Some(arrow) = after.find("->") {
  // map_py_type_ts(after[arrow + 2..].trim())
  // } else {
  // "void"
  // };
  // let ts_params = translate_py_params_ts(params);
  // let (body, consumed) = collect_py_body(lines.as_slice(), i);
  // 
  // let prefix = if is_async { "export async function" } else { "export function" };
  // out.push_str(&format!("{} {}({}): {} {{\n", prefix, name, ts_params, ret_type));
  // for bl in &body {
  // out.push_str(&format!("    // TODO: {}\n", bl.trim()));
  // }
  // out.push_str("}\n\n");
  // i += consumed;
  // continue;
  // }
  // }
  // }
  // 
  // out.push_str(&format!("// {}\n", line));
  // i += 1;
  // }
  // 
  // out
  // }
  // 
  // // ===========================================================================
  // // Shared helpers
  // // ===========================================================================
  // 
  // fn parse_ts_field(line: &str) -> Option<(&str, &str)> {
  // let clean = line.trim().trim_end_matches(';').trim_end_matches(',');
  // let colon = clean.find(':')?;
  // let name = clean[..colon].trim();
  // let ty = clean[colon + 1..].trim();
  // Some((name, ty))
  // }
  // 
  // fn translate_ts_params_rust(params_str: &str) -> String {
  // let mut parts = Vec::new();
  // for part in params_str.split(',') {
  // let trimmed = part.trim();
  // if trimmed.is_empty() {
  // continue;
  // }
  // let mut pieces = trimmed.splitn(2, ':');
  // let name = pieces.next().unwrap_or("").trim();
  // let ty = pieces.next().unwrap_or("any").trim();
  // let clean_name = name.trim_end_matches('?');
  // let rust_ty = map_ts_type_rust(ty);
  // parts.push(format!("{}: {}", clean_name, rust_ty));
  // }
  // parts.join(", ")
  // }
  // 
  // fn translate_ts_params_python(params_str: &str) -> String {
  // let mut parts = Vec::new();
  // for part in params_str.split(',') {
  // let trimmed = part.trim();
  // if trimmed.is_empty() {
  // continue;
  // }
  // let mut pieces = trimmed.splitn(2, ':');
  // let name = pieces.next().unwrap_or("").trim().trim_end_matches('?');
  // let ty = pieces.next().unwrap_or("").trim();
  // let py_ty = map_ts_type_python(ty);
  // if py_ty.is_empty() {
  // parts.push(name.to_string());
  // } else {
  // parts.push(format!("{}: {}", name, py_ty));
  // }
  // }
  // parts.join(", ")
  // }
  // 
  // fn translate_ts_params_go(params_str: &str) -> String {
  // let mut parts = Vec::new();
  // for part in params_str.split(',') {
  // let trimmed = part.trim();
  // if trimmed.is_empty() {
  // continue;
  // }
  // let mut pieces = trimmed.splitn(2, ':');
  // let name = pieces.next().unwrap_or("").trim().trim_end_matches('?');
  // let ty = pieces.next().unwrap_or("any").trim();
  // let go_ty = map_ts_type_go(ty);
  // parts.push(format!("{} {}", name, go_ty));
  // }
  // parts.join(", ")
  // }
  // 
  // fn translate_py_params_go(params_str: &str) -> String {
  // let mut parts = Vec::new();
  // for part in params_str.split(',') {
  // let trimmed = part.trim();
  // if trimmed.is_empty() || trimmed == "self" {
  // continue;
  // }
  // if let Some((name, ty)) = trimmed.split_once(':') {
  // let name = name.trim();
  // let ty = ty.split('=').next().unwrap_or("").trim();
  // let go_ty = map_py_type_go(ty);
  // parts.push(format!("{} {}", name, go_ty));
  // } else {
  // let name = trimmed.split('=').next().unwrap_or(trimmed).trim();
  // parts.push(format!("{} interface{{}}", name));
  // }
  // }
  // parts.join(", ")
  // }
  // 
  // fn translate_py_params_ts(params_str: &str) -> String {
  // let mut parts = Vec::new();
  // for part in params_str.split(',') {
  // let trimmed = part.trim();
  // if trimmed.is_empty() || trimmed == "self" {
  // continue;
  // }
  // if let Some((name, ty)) = trimmed.split_once(':') {
  // let name = name.trim();
  // let ty = ty.split('=').next().unwrap_or("").trim();
  // let ts_ty = map_py_type_ts(ty);
  // parts.push(format!("{}: {}", name, ts_ty));
  // } else {
  // let name = trimmed.split('=').next().unwrap_or(trimmed).trim();
  // parts.push(format!("{}: any", name));
  // }
  // }
  // parts.join(", ")
  // }
  // 
  // fn translate_rust_params_ts(params_str: &str) -> String {
  // let mut parts = Vec::new();
  // for part in params_str.split(',') {
  // let trimmed = part.trim();
  // if trimmed.is_empty() {
  // continue;
  // }
  // if let Some((name, ty)) = trimmed.split_once(':') {
  // let name = name.trim();
  // let ty = ty.trim();
  // let ts_ty = map_rust_type_ts(ty);
  // parts.push(format!("{}: {}", name, ts_ty));
  // } else {
  // parts.push(format!("{}: any", trimmed));
  // }
  // }
  // parts.join(", ")
  // }
  // 
  // // ---------------------------------------------------------------------------
  // // Type mapping tables
  // // ---------------------------------------------------------------------------
  // 
  // fn map_ts_type_rust(ts_type: &str) -> &'static str {
  // match ts_type.trim() {
  // "string" => "String",
  // "number" => "i32",
  // "boolean" | "bool" => "bool",
  // "void" => "()",
  // "any" | "unknown" => "String",
  // "null" | "undefined" => "()",
  // "string[]" | "Array<string>" => "Vec<String>",
  // "number[]" | "Array<number>" => "Vec<i32>",
  // "boolean[]" | "Array<boolean>" => "Vec<bool>",
  // "Date" => "String",
  // "Buffer" | "Uint8Array" => "Vec<u8>",
  // "object" | "Record<string, any>" => "std::collections::HashMap<String, String>",
  // "Promise<string>" => "String",
  // "Promise<number>" => "i32",
  // "Promise<void>" => "()",
  // _ => "String",
  // }
  // }
  // 
  // fn map_rust_type_ts(rust_type: &str) -> &'static str {
  // let t = rust_type.trim().trim_end_matches(',');
  // match t {
  // "String" | "&str" => "string",
  // "i32" | "i64" | "u32" | "u64" | "usize" | "isize" | "f32" | "f64" => "number",
  // "bool" => "boolean",
  // "()" => "void",
  // s if s.starts_with("Option<") => "any",
  // s if s.starts_with("Vec<") => "any[]",
  // s if s.starts_with("&[") => "any[]",
  // _ => "any",
  // }
  // }
  // 
  // fn map_ts_type_python(ts_type: &str) -> &'static str {
  // match ts_type.trim() {
  // "string" => "str",
  // "number" => "int",
  // "boolean" | "bool" => "bool",
  // "void" => "None",
  // "any" | "unknown" => "",
  // "string[]" | "Array<string>" => "list[str]",
  // "number[]" | "Array<number>" => "list[int]",
  // _ => "",
  // }
  // }
  // 
  // fn map_ts_type_go(ts_type: &str) -> &'static str {
  // match ts_type.trim() {
  // "string" => "string",
  // "number" => "int",
  // "boolean" | "bool" => "bool",
  // "void" => "",
  // "any" | "unknown" => "interface{}",
  // "string[]" | "Array<string>" => "[]string",
  // "number[]" | "Array<number>" => "[]int",
  // _ => "interface{}",
  // }
  // }
  // 
  // fn map_py_type_go(py_type: &str) -> &'static str {
  // match py_type.trim() {
  // "str" => "string",
  // "int" => "int",
  // "float" => "float64",
  // "bool" => "bool",
  // "None" => "",
  // "list" | "List" => "[]interface{}",
  // "dict" | "Dict" => "map[string]interface{}",
  // _ => "interface{}",
  // }
  // }
  // 
  // fn map_py_type_ts(py_type: &str) -> &'static str {
  // match py_type.trim() {
  // "str" => "string",
  // "int" | "float" => "number",
  // "bool" => "boolean",
  // "None" => "void",
  // "list" | "List" => "any[]",
  // "dict" | "Dict" => "Record<string, any>",
  // _ => "any",
  // }
  // }
  // 
  // // ---------------------------------------------------------------------------
  // // Body collectors
  // // ---------------------------------------------------------------------------
  // 
  // /// Collect braces-delimited body lines for JS/TS/Go/Rust/Java.
  // fn collect_braced_body(lines: &[&str], start: usize) -> (Vec<String>, usize) {
  // let mut body = Vec::new();
  // let mut brace_depth = 0;
  // let mut found_open = false;
  // let mut i = start;
  // 
  // while i < lines.len() {
  // let line = lines[i];
  // for c in line.chars() {
  // if c == '{' {
  // brace_depth += 1;
  // found_open = true;
  // } else if c == '}' {
  // brace_depth -= 1;
  // }
  // }
  // 
  // if found_open && i > start {
  // if brace_depth > 0 {
  // body.push(line.to_string());
  // } else {
  // // closing brace line — don't include it
  // i += 1;
  // break;
  // }
  // }
  // 
  // i += 1;
  // 
  // if found_open && brace_depth == 0 {
  // break;
  // }
  // }
  // 
  // let consumed = i - start;
  // (body, consumed)
  // }
  // 
  // /// Collect indentation-based body for Python.
  // fn collect_py_body(lines: &[&str], start: usize) -> (Vec<String>, usize) {
  // let mut body = Vec::new();
  // let base_indent = leading_spaces(lines[start]);
  // let mut i = start + 1;
  // 
  // while i < lines.len() {
  // let line = lines[i];
  // if line.trim().is_empty() {
  // body.push(String::new());
  // i += 1;
  // continue;
  // }
  // let indent = leading_spaces(line);
  // if indent <= base_indent {
  // break;
  // }
  // body.push(line.to_string());
  // i += 1;
  // }
  // 
  // let consumed = i - start;
  // (body, consumed)
  // }
  // 
  // fn leading_spaces(s: &str) -> usize {
  // s.len() - s.trim_start().len()
  // }
  // 
  // // ---------------------------------------------------------------------------
  // // Name converters
  // // ---------------------------------------------------------------------------
  // 
  // fn to_snake_case(name: &str) -> String {
  // let mut result = String::new();
  // for (i, c) in name.chars().enumerate() {
  // if c.is_uppercase() {
  // if i > 0 {
  // result.push('_');
  // }
  // result.push(c.to_lowercase().next().unwrap());
  // } else {
  // result.push(c);
  // }
  // }
  // result
  // }
  // 
  // fn to_pascal_case(name: &str) -> String {
  // name.split('_')
  // .map(|part| {
  // let mut chars = part.chars();
  // match chars.next() {
  // None => String::new(),
  // Some(first) => {
  // let mut s = first.to_uppercase().to_string();
  // s.extend(chars);
  // s
  // }
  // }
  // })
  // .collect()
  // }
  // 
  // fn strip_markdown_fences(text: &str) -> String {
  // let mut s = text.trim().to_string();
  // if s.starts_with("```") {
  // if let Some(pos) = s.find('\n') {
  // s = s[pos + 1..].to_string();
  // }
  // }
  // if s.ends_with("```") {
  // if let Some(pos) = s.rfind("```") {
  // s = s[..pos].to_string();
  // }
  // }
  // s.trim().to_string()
  // }
  // 
  // // ===========================================================================
  // // Tests
  // // ===========================================================================
  // 
  // #[cfg(test)]
  // mod tests {
  // use super::*;
  // 
  // #[test]
  // fn test_ts_function_to_rust() {
  // let ts = r#"export function greet(name: string): string {
  // return `Hello, ${name}`;
  // }
  // 
  // export function add(a: number, b: number): number {
  // return a + b;
  // }
  // "#;
  // let rust = translate_ts_to_rust(ts);
  // assert!(rust.contains("pub fn greet("));
  // assert!(rust.contains("-> String"));
  // assert!(rust.contains("pub fn add("));
  // assert!(rust.contains("-> i32"));
  // }
  // 
  // #[test]
  // fn test_ts_interface_to_rust() {
  // let ts = r#"export interface User {
  // id: number;
  // name: string;
  // email?: string;
  // }
  // "#;
  // let rust = translate_ts_to_rust(ts);
  // assert!(rust.contains("pub struct User"));
  // assert!(rust.contains("pub id: i32"));
  // assert!(rust.contains("pub name: String"));
  // assert!(rust.contains("Option<String>"));
  // }
  // 
  // #[test]
  // fn test_py_function_to_rust() {
  // let py = r#"def greet(name: str) -> str:
  // return f"Hello, {name}"
  // 
  // def add(a: int, b: int) -> int:
  // return a + b
  // "#;
  // let rust = translate_py_to_rust(py);
  // assert!(rust.contains("pub fn greet("));
  // assert!(rust.contains("-> String"));
  // assert!(rust.contains("pub fn add("));
  // assert!(rust.contains("-> i64"));
  // }
  // 
  // #[test]
  // fn test_ts_to_python() {
  // let ts = r#"export function greet(name: string): string {
  // return `Hello, ${name}`;
  // }
  // "#;
  // let py = translate_ts_to_python(ts);
  // assert!(py.contains("def greet(name: str):"));
  // }
  // 
  // #[test]
  // fn test_ts_to_go() {
  // let ts = r#"export function greet(name: string): string {
  // return `Hello, ${name}`;
  // }
  // "#;
  // let go_code = translate_ts_to_go(ts);
  // assert!(go_code.contains("package main"));
  // assert!(go_code.contains("func Greet("));
  // assert!(go_code.contains("string"));
  // }
  // 
  // #[test]
  // fn test_snake_case() {
  // assert_eq!(to_snake_case("getUserName"), "get_user_name");
  // assert_eq!(to_snake_case("greet"), "greet");
  // }
  // 
  // #[test]
  // fn test_pascal_case() {
  // assert_eq!(to_pascal_case("get_user_name"), "GetUserName");
  // assert_eq!(to_pascal_case("greet"), "Greet");
  // }
  // }
}

