use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{anyhow, Result};

use super::detect::{tool_available, Language};

/// Scaffold and initialize a project for the target language, including
/// installing dependencies.
pub fn scaffold_project(output_dir: &Path, lang: Language) -> Result<String> {
    let mut log = String::new();

    // Check that the required build tool exists on this machine. For some
    // targets (like TypeScript/JavaScript) we can still scaffold a bare
    // project even if the ecosystem tool is missing.
    let tool = lang.required_tool();
    let has_tool = tool_available(tool);

    fs::create_dir_all(output_dir)?;

    match lang {
        Language::Java if !has_tool => {
            return Err(anyhow!(
                "Required tool `{}` for {} was not found on your system. \
                 Please install it before running this migration.",
                tool,
                lang
            ));
        }
        Language::Rust => scaffold_rust(output_dir, &mut log)?,
        Language::Go => scaffold_go(output_dir, &mut log)?,
        Language::TypeScript => {
            if has_tool {
                scaffold_typescript(output_dir, &mut log)?
            } else {
                let src = output_dir.join("src");
                fs::create_dir_all(&src)?;
                let _ = writeln!(
                    &mut log,
                    "  ⚠ npm not found; created bare TypeScript src/ tree without npm/tsconfig."
                );
            }
        }
        Language::JavaScript => {
            if has_tool {
                scaffold_javascript(output_dir, &mut log)?
            } else {
                let src = output_dir.join("src");
                fs::create_dir_all(&src)?;
                let _ = writeln!(
                    &mut log,
                    "  ⚠ npm not found; created bare JavaScript src/ tree without npm init."
                );
            }
        }
        Language::React | Language::Vue | Language::Svelte => {
            if has_tool {
                scaffold_vite(output_dir, lang, &mut log)?
            } else {
                return Err(anyhow!("npm is required to scaffold Vite-based projects"));
            }
        }
        Language::NextJs => {
            if has_tool {
                scaffold_nextjs(output_dir, &mut log)?
            } else {
                return Err(anyhow!("npm/npx is required to scaffold Next.js projects"));
            }
        }
        Language::Python => scaffold_python(output_dir, &mut log)?,
        Language::Java => scaffold_java(output_dir, &mut log)?,
        Language::Cpp | Language::Assembly => {
            let _ = writeln!(&mut log, "  ⚠ Scaffolding for {} is not yet automated", lang);
        }
    }

    Ok(log)
}

// ---------------------------------------------------------------------------
// Per-language scaffolders
// ---------------------------------------------------------------------------

fn scaffold_rust(dir: &Path, log: &mut String) -> Result<()> {
    let src = dir.join("src");
    fs::create_dir_all(&src)?;

    // Cargo.toml
    let name = dir_name(dir);
    let cargo_toml = format!(
        "[package]\nname = \"{}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nanyhow = \"1\"\nserde = {{ version = \"1\", features = [\"derive\"] }}\nserde_json = \"1\"\n",
        name
    );
    fs::write(dir.join("Cargo.toml"), cargo_toml)?;

    // src/lib.rs placeholder
    fs::write(
        src.join("lib.rs"),
        "// Auto-generated by astra migrate\n",
    )?;

    let _ = writeln!(log, "  ✓ Created Rust project at {:?}", dir);

    // Try running cargo check to pull deps
    let status = Command::new("cargo")
        .arg("check")
        .current_dir(dir)
        .status();

    match status {
        Ok(s) if s.success() => {
            let _ = writeln!(log, "  ✓ Dependencies installed (cargo check passed)");
        }
        _ => {
            let _ = writeln!(log, "  ⚠ cargo check didn't succeed — deps may need manual install");
        }
    }

    Ok(())
}

fn scaffold_go(dir: &Path, log: &mut String) -> Result<()> {
    fs::create_dir_all(dir)?;

    let mod_name = dir_name(dir);
    let status = Command::new("go")
        .args(["mod", "init", &mod_name])
        .current_dir(dir)
        .status();

    match status {
        Ok(s) if s.success() => {
            let _ = writeln!(log, "  ✓ Initialized Go module `{}`", mod_name);
        }
        _ => {
            // Fallback: write a go.mod manually
            let go_mod = format!("module {}\n\ngo 1.21\n", mod_name);
            fs::write(dir.join("go.mod"), go_mod)?;
            let _ = writeln!(log, "  ✓ Created go.mod manually");
        }
    }

    Ok(())
}

fn scaffold_typescript(dir: &Path, log: &mut String) -> Result<()> {
    let src = dir.join("src");
    fs::create_dir_all(&src)?;

    // npm init
    let init_status = Command::new("npm")
        .args(["init", "-y"])
        .current_dir(dir)
        .status();

    if let Ok(s) = init_status {
        if s.success() {
            let _ = writeln!(log, "  ✓ npm init -y");
        }
    }

    // Install typescript
    let install_status = Command::new("npm")
        .args(["install", "--save-dev", "typescript", "@types/node"])
        .current_dir(dir)
        .status();

    if let Ok(s) = install_status {
        if s.success() {
            let _ = writeln!(log, "  ✓ Installed typescript, @types/node");
        }
    }

    // tsconfig
    let tsconfig = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*"]
}
"#;
    fs::write(dir.join("tsconfig.json"), tsconfig)?;
    let _ = writeln!(log, "  ✓ Created tsconfig.json");

    Ok(())
}

fn scaffold_javascript(dir: &Path, log: &mut String) -> Result<()> {
    let src = dir.join("src");
    fs::create_dir_all(&src)?;

    let init_status = Command::new("npm")
        .args(["init", "-y"])
        .current_dir(dir)
        .status();

    if let Ok(s) = init_status {
        if s.success() {
            let _ = writeln!(log, "  ✓ npm init -y");
        }
    }

    Ok(())
}

fn scaffold_python(dir: &Path, log: &mut String) -> Result<()> {
    let pkg = dir.join("src");
    fs::create_dir_all(&pkg)?;
    fs::write(pkg.join("__init__.py"), "# Auto-generated by astra migrate\n")?;

    // pyproject.toml
    let name = dir_name(dir);
    let pyproject = format!(
        "[project]\nname = \"{}\"\nversion = \"0.1.0\"\nrequires-python = \">=3.9\"\n",
        name
    );
    fs::write(dir.join("pyproject.toml"), pyproject)?;
    let _ = writeln!(log, "  ✓ Created Python project at {:?}", dir);

    // Try to create a venv
    let venv_status = Command::new("python")
        .args(["-m", "venv", ".venv"])
        .current_dir(dir)
        .status();

    if let Ok(s) = venv_status {
        if s.success() {
            let _ = writeln!(log, "  ✓ Created virtual environment (.venv)");
        }
    }

    Ok(())
}

fn scaffold_java(dir: &Path, log: &mut String) -> Result<()> {
    let src = dir.join("src").join("main").join("java");
    fs::create_dir_all(&src)?;
    let _ = writeln!(log, "  ✓ Created Java source tree at {:?}", src);
    Ok(())
}

fn scaffold_vite(dir: &Path, lang: Language, log: &mut String) -> Result<()> {
    let template = match lang {
        Language::React => "react-ts",
        Language::Vue => "vue-ts",
        Language::Svelte => "svelte-ts",
        _ => "vanilla-ts",
    };

    let dir_str = dir.to_string_lossy();
    let npm_cmd = if cfg!(windows) { "npm.cmd" } else { "npm" };
    
    let output = Command::new(npm_cmd)
        .args(["create", "vite@latest", &dir_str, "--", "--template", template])
        .output()?;

    if output.status.success() {
        let _ = writeln!(log, "  ✓ Scaffolded {} via Vite", template);
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let _ = writeln!(log, "  ⚠ Failed to scaffold Vite: {}", stderr);
    }
    
    Ok(())
}

fn scaffold_nextjs(dir: &Path, log: &mut String) -> Result<()> {
    let dir_str = dir.to_string_lossy();
    let npx_cmd = if cfg!(windows) { "npx.cmd" } else { "npx" };
    
    let output = Command::new(npx_cmd)
        .args([
            "--yes",
            "create-next-app@latest",
            &dir_str,
            "--typescript",
            "--tailwind",
            "--eslint",
            "--app",
            "--src-dir",
            "--import-alias",
            "@/*",
            "--use-npm"
        ])
        .output()?;

    if output.status.success() {
        let _ = writeln!(log, "  ✓ Scaffolded Next.js App Router project (with Tailwind)");
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let _ = writeln!(log, "  ⚠ Failed to scaffold Next.js: {}", stderr);
    }
    
    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn dir_name(dir: &Path) -> String {
    dir.file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("project")
        .to_string()
}
